### ISSUE TITLE
TT 1.0.0 - Tools and Equipment

### ISSUE THREAD

**Issue by divyanshisuri** [divyanshisuri/divya-srepo#2]
**Part 1 - Fastpages**

- [ ] Build personal Fastpages / GitHub pages “_post” share the following.
 - [ ] Share link to personal Fastpages / GitHub pages running on github.io.
 - [ ] Share link to a new page (_posts) in your Fastpages project show use of Markdown and/or HTML fragments. You will need to l learn special date requirements of a file as well as a little Markdown or HTML.
 - [ ] Share link to Python Jupyter notebook (_notebooks) showing usage of Python: print (“Hello”)
 - [ ] Share link to Java Jupyter notebook (_notebooks) showing usage of Java: System.out.println(“Hello”)
 - [ ] Capture image/screen capture of Fastpages project showing use of an Integrated Development Environment (VS Studio)
 - [ ] Share link showing your GitHub insights. This is your personal activity of commit history.

**Part 2 - Java Project**

 - [ ] Screen Capture Java project running on personal laptop localhost:0.0.0.0:8080
 - [ ] Share link of GitHub code commit Java on project
